# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-29 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import spacelaunchnow.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180429_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='image_url',
            field=models.FileField(blank=True, default=None, null=True, storage=spacelaunchnow.storage_backends.ImageStorage(), upload_to=b''),
        ),
    ]
